@extends('layouts.app')

@section('contents')
    <style>
        .product-list {
            max-height: 580px;
            overflow: auto;
        }
    </style>

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Delivery Receipt</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- Content Header (Page header) -->


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Print Delivery Receipt</h3>
            </div>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-md-8">
                        <div>DR No. </div>
                        <hr style="border-top: 1px dashed">
                        <div>Generated By: </div>
                        <br>
                        <table class="table table-bordered table-striped product-list">
                            <thead>
                                <tr>
                                    <th>Product Type</th>
                                    <th>Quantity</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>--</td>
                                    <td>--</td>
                                    <td>--</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-4">
                    <style>
            body{ font-family:"Arial",Helvetica,sans-serif;font-size: 9pt;word-wrap: break-word; }
            hr { border: 0; border-top: 1px solid #000; margin: 10px 0; }
            td { font-family:"Arial",Helvetica,sans-serif;font-size: 9pt;word-wrap: break-word; }
            </style>
                        <table width="100%">
                            <tr><td colspan='4'><center>EOLF FOOD TRADING OPC</center></td></tr> 
                            <tr><td colspan='4'><center>DELIVERY RECEIPT</center></td></tr> 
                            <tr><td colspan='4'>DR No.:  03-245281</td></tr>   
                            <tr><td colspan='4'>Date:  6/3/2024</td></tr>   
                            <tr><td colspan='4'>Distributor:  PC 03</td></tr>   
                            <tr><td>Qty</td><td>Items</td><td>Price</td><td align="right">Amount</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                            <tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>
                        </table>
                        <hr>
                        <table width="100%">
                            <tr><td align="left">Total Sales:</td><td align="right">1,022,615.00</td></tr>
                            <tr><td align="left">Less BO:</td><td align="right">0.00</td></tr>
                            <tr><td align="left">Discount (%):</td><td align="right">0.00%</td></tr>
                            <tr><td align="left">Total Amount:</td><td align="right">1,022,615.00</td></tr>
                        </table>
                        <br>
                        <br>
                        <br>
                        ---------------------------------<br>
                        Andal, Froilan<br>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="d-flex">
                    <div class="p-2"><button type="submit" class="btn btn-success btn-print" onclick="printPage()"><i class="fa-solid fa-print"></i> Print</button></div>
                    <div class="p-2"><a href="/orders" class="btn btn-danger btn-print"><i class="fa-solid fa-xmark"></i> Close</a></div>
                </div>
            </div>
 

            <script>
function printPage() {
    // Hide the print button before printing
    var printButton = document.querySelector('.btn-print');
    if (printButton) {
        printButton.style.display = 'none';
    }

    // Create a new window for printing
    var mywindow = window.open('', 'PRINT', 'height=600,width=600');
    mywindow.document.write('<html><head><title>DELIVERY RECEIPT</title>');
    mywindow.document.write('<style>');
    mywindow.document.write('body{ font-family:"Arial",Helvetica,sans-serif;font-size: 9pt;word-wrap: break-word; }');
    mywindow.document.write('hr { border: 0; border-top: 1px solid #000; margin: 10px 0; }');
    mywindow.document.write('td { font-family:"Arial",Helvetica,sans-serif;font-size: 9pt;word-wrap: break-word; }');
    mywindow.document.write('</style>');
    mywindow.document.write('</head><body>');
    mywindow.document.write('<center>EOLF FOOD TRADING OPC</center><br>');
    mywindow.document.write('<center>DELIVERY RECEIPT</center><br>');
    mywindow.document.write('<br><br>');
    mywindow.document.write('DR No.:  03-245281<br>');
    mywindow.document.write('Date:  6/3/2024<br>');
    mywindow.document.write('Distributor:  PC 03<br>');
    mywindow.document.write('<table width="100%">');
    mywindow.document.write('<tr><td>Qty</td><td>Items</td><td>Price</td><td align="right">Amount</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('<tr><td>36</td><td>SC</td><td>552.00</td><td align="right">19,872.00</td></tr>');
    mywindow.document.write('</table>');
    mywindow.document.write('<hr>');
    mywindow.document.write('<table width="100%">');
    mywindow.document.write('<tr><td align="left">Total Sales:</td><td align="right">1,022,615.00</td></tr>');
    mywindow.document.write('<tr><td align="left">Less BO:</td><td align="right">0.00</td></tr>');
    mywindow.document.write('<tr><td align="left">Discount (%):</td><td align="right">0.00%</td></tr>');
    mywindow.document.write('<tr><td align="left">Total Amount:</td><td align="right">1,022,615.00</td></tr>');
    mywindow.document.write('</table>');
    mywindow.document.write('<br><br><br>');
    mywindow.document.write('---------------------------------<br>');
    mywindow.document.write('Andal, Froilan<br>');
    mywindow.document.write('</body></html>');

    mywindow.document.close(); // Necessary for IE >= 10
    mywindow.focus(); // Necessary for IE >= 10

            mywindow.print();
            mywindow.close();
}
</script>





    </section>
@endsection
<!-- /.content -->
