@extends('layouts.app')

@section('contents')
    <style>
        .product-list {
            max-height: 580px;
            overflow: auto;
        }
    </style>

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Delivery Receipt</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- Content Header (Page header) -->


    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Print Delivery Receipt</h3>


            </div>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-md-8">
                        <div>DR No. </div>
                        <hr style="border-top: 1px dashed">
                        <div>Generated By: </div>
                        <br>

                        <table class="table table-bordered table-striped product-list">
                            <thead>
                                <tr>
                                    <th>Product Type</th>
                                    <th>Quantity</th>
                                    <th>Amount</th>

                                </tr>
                            </thead>
                            <tbody>


                                <tr>
                                    <td>--</td>
                                    <td>--</td>
                                    <td>--</td>


                                </tr>

                            </tbody>

                        </table>
                        <div class="col-md-4">
                        </div>
                    </div>
                </div>




            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <div class="d-flex">
                    <div class="p-2"><button type="submit" class="btn btn-success btn-print" onclick="printPage()"><i
                                class="fa-solid fa-print"></i> Print</button></div>
                    <div class="p-2"><a href="/orders" class="btn btn-danger btn-print"><i class="fa-solid fa-xmark"></i>
                            Close</a></div>

                </div>

            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

        <script>
            function printPage() {
                // Hide the print button before printing
                var printButton = document.querySelector('.btn-print');
                if (printButton) {
                    printButton.style.display = 'none';
                }
                // Trigger the print dialog
                window.print();
                // Show the print button after printing is done (optional)
                if (printButton) {
                    printButton.style.display = 'block';
                }
            }
        </script>


    </section>
@endsection
<!-- /.content -->
