@extends('layouts.app')


@section('custom_css')
    <style>
        .product-list {
            max-height: 580px;
            overflow: auto;
        }

        hr {
            border: 0;
            border-top: 1px solid #000;
            margin: 10px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid black;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        td {
            text-align: left;
        }
    </style>
@endsection

@section('contents')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- Content Header -->
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Delivery Receipt</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Print Delivery Receipt</h3>
            </div>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-md-8">
                        <div>DR No. {{ $deliveryReceipt->id }}</div>
                        <hr>
                        <div>Generated By: {{ $deliveryReceipt->generated_by }}</div>
                        <br>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Product Type</th>
                                    <th>Quantity</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>


                                @foreach ($products as $product)

                                    <tr>
                                        <td>{{ $product['ptype_code'] }}</td>
                                        <td>{{ $product['total'] }}</td>
                                        <td>{{ $product['price'] }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-4">

                        <div class="text-center">
                            EOLF FOOD TRADING OPC
                            <br>
                            DELIVERY RECEIPT

                        </div>

                        <div class="">
                            DR No.: {{ $deliveryReceipt->id }} <br>
                            Date: {{ $deliveryReceipt->date }}
                        </div>
                        <table width="100%">
                            <tr>
                                <td>Qty</td>
                                <td>Items</td>
                                <td>Price</td>
                                <td align="right">Amount</td>
                            </tr>

                            @php $totalSales = 0; @endphp

                            @foreach ($products as $product)
                                @php   $totalSales += $product['total'] * $product['price'];  @endphp
                                <tr>
                                    <td>{{ $product['ptype_code'] }}</td>
                                    <td>{{ $product['total'] }}</td>
                                    <td>{{ $product['price'] }}</td>
                                    <td>{{ formatNumber($product['total'] * $product['price']) }}</td>
                                </tr>
                            @endforeach

                        </table>


                        <div class="">
                                Total Sales:
                               {{ formatNumber($totalSales) }} <br>
                                Less BO:
                                {{ formatNumber($deliveryReceipt->bad_orders) }} <br>
                                Discount (%):
                                {{ formatNumber($deliveryReceipt->discount) }} <br>
                                Total Amount:
                                {{ formatNumber($deliveryReceipt->total_amount) }} <br>
                        </div>
                        <br><br><br>
                        ---------------------------------<br>
                        Andal, Froilan<br>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="d-flex">
                    <div class="p-2">
                        <button type="button" class="btn btn-success btn-print" onclick="printPage()">
                            <i class="fa-solid fa-print"></i> Print
                        </button>
                    </div>
                    <div class="p-2">
                        <a href="/" class="btn btn-danger btn-print">
                            <i class="fa-solid fa-xmark"></i> Close
                        </a>
                    </div>
                </div>
            </div>
        </div>


    </section>
@endsection

@section('custom_js')
    <script>
        function printPage() {
            // Hide the print button before printing
            var printButton = document.querySelector('.btn-print');
            if (printButton) {
                printButton.style.display = 'none';
            }

            // Create a new window for printing
            var mywindow = window.open('', 'PRINT', 'height=600,width=600');
            mywindow.document.write('<html><title>DELIVERY RECEIPT</title>');
            mywindow.document.write('<style>');
            mywindow.document.write(
                'body{ font-family:"Arial",Helvetica,sans-serif;font-size: 9pt;word-wrap: break-word; }');
            mywindow.document.write('hr { border: 0; border-top: 1px solid #000; margin: 10px 0; }');
            mywindow.document.write(
                'table { border-collapse: collapse; } td { font-family:"Arial",Helvetica,sans-serif;font-size: 9pt;word-wrap: break-word; padding: 3px; } @media print { body { margin: 0 0 3px 3px; } } @page { margin: 0 0 3px 3px; }');
            mywindow.document.write('</style>');
            mywindow.document.write('</head><body>');
            mywindow.document.write('<center>EOLF FOOD TRADING OPC</center><br>');
            mywindow.document.write('<center>DELIVERY RECEIPT</center><br>');
            mywindow.document.write('<br><br>');
            mywindow.document.write('DR No.: {{ $deliveryReceipt->id }}<br>');
            mywindow.document.write('Date: {{ $deliveryReceipt->date }}<br>');
            mywindow.document.write('<table cellp width="100%">');
            mywindow.document.write('<tr><td>Qty</td><td>Items</td><td>Price</td><td align="right">Amount</td></tr>');
            @foreach ($products as $product)
                mywindow.document.write(
                    '<tr><td>{{ $product['total'] }}</td><td>{{ $product['ptype_code'] }}</td><td>{{ $product['price'] }}</td><td align="right">{{ formatNumber($product['total'] * $product['price']) }}</td></tr>'
                );
            @endforeach
            mywindow.document.write('</table>');
            mywindow.document.write(
                '<br>Total Sales: {{ formatNumber($totalSales) }} <br>'
            );
            mywindow.document.write(
                'Less BO: {{ formatNumber($deliveryReceipt->bad_orders) }} <br>');
            mywindow.document.write(
                'Discount (%): {{ formatNumber($deliveryReceipt->discount) }} <br>'
            );
            mywindow.document.write(
                'Total Amount: {{ formatNumber($deliveryReceipt->total_amount) }} <br>'
            );
            mywindow.document.write('</table>');
            mywindow.document.write('<br><br><br>');
            mywindow.document.write('---------------------------------<br>');
            mywindow.document.write('Andal, Froilan<br>');
            mywindow.document.write('</body></html>');

            mywindow.document.close(); // Necessary for IE >= 10
            mywindow.focus(); // Necessary for IE >= 10

            mywindow.print();
            mywindow.close();
        }
    </script>
@endsection
