@extends('layouts.app')

@section('custom_css')
@endsection

@section('contents')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Order Slips</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Order Slips</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="content">

        @include('layouts.errors')

        <form action="{{ route('print-ticket') }}" method="POST">
            @csrf
            <div class="card">
                <div class="card-body">
                    <div class="">
                        <a href="{{ route('generate-order-slip') }}" class="btn btn-primary">Generate Order Slip</a>
                    </div>
                    <div class="tbContainer">

                        <table id="example3" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Delivery Person</th>
                                    <th>Generated by</th>
                                    <th>Checked by</th>
                                    <th>Remarks</th>
                                    <th>Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($orderSlips as $oslip)
                                    <tr>
                                        <td>{{ $oslip->code }}</td>
                                        <td>{{ $oslip->delivery_person }}</td>
                                        <td>{{ $oslip->generated_by }}</td>
                                        <td>{{ $oslip->checked_by }}</td>
                                        <td>{{ $oslip->remarks }}</td>
                                        <td>{{ $oslip->created_at }}</td>
                                        <td>
                                            <a href="{{ route('report.orderSlip', ['code' => $oslip->code]) }}"
                                                class="btn btn-default">Print</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </form>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection
